services:
  front:
    stdin_open: true
    image: akhmetovsr/tgrepository1:ncity

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/g-coin.store/fullchain.pem:/etc/nginx/ssl/live/g-coin.store/fullchain.pem
      - /etc/letsencrypt/live/g-coin.store/privkey.pem:/etc/nginx/ssl/live/g-coin.store/privkey.pem
      - /etc/letsencrypt/live/g-coin.store/cert.pem:/etc/nginx/ssl/live/g-coin.store/cert.pem
      - /etc/letsencrypt/live/g-coin.store/chain.pem:/etc/nginx/ssl/live/g-coin.store/chain.pem

      - /etc/letsencrypt/options-ssl-nginx.conf:/letsencrypt/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/letsencrypt/ssl-dhparams.pem